module.exports = {
  'WRONG_PARAMS': 400,
  'SUCCESS': 200,
  'FAIL': 300,
  'SYSTEM_ERROR': 500,
  "EXPIRE_TOKEN_VIMO": "713",
  'REQUEST_CHARGE_WITHOUT_OTP': "715",
  "VIMO_GATEWAY_SUCCESS": "00"
}
